{
 "title": "VMware ESXi",
 "tags": [
  "prometheus",
  "vmware",
  "esxi"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "esxhost",
    "label": "esxhost",
    "query": "label_values(vmware_host_boot_timestamp_seconds,host_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "HOST STATUS",
   "type": "stat",
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vmware_host_power_state{host_name=~\"$esxhost\"}"
    }
   ]
  },
  {
   "title": "DISK STATUS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vmware_host_disk_ok{host_name=~\"$esxhost\"}"
    }
   ]
  },
  {
   "title": "DataStore Capacity Remaining",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vmware_datastore_freespace_size"
    }
   ]
  },
  {
   "title": "Host Memory Remaining",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vmware_host_memory_max - vmware_host_memory_usage"
    }
   ]
  },
  {
   "title": "ESXi Host Uptime Since",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsUS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( vmware_host_boot_timestamp_seconds{host_name=~\"$esxhost\"} - 24000 )* 1000"
    }
   ]
  },
  {
   "title": "Host CPU usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(vmware_host_cpu_usage{host_name=~\"$esxhost\"}) * 100 / (vmware_host_cpu_max{host_name=~\"$esxhost\"})"
    }
   ]
  },
  {
   "title": "DS datastore1 usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((vmware_datastore_capacity_size{host_name=~\"$esxhost\", ds_name=~\"datastore1\"}) - (vmware_datastore_freespace_size{host_name=~\"$esxhost\", ds_name=~\"datastore1\"})) * 100 / (vmware_datastore_capacity_size{host_name=~\"$esxhost\", ds_name=~\"datastore1\"})"
    }
   ]
  },
  {
   "title": "Host Memory usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(vmware_host_memory_usage{host_name=~\"$esxhost\"}) * 100 / (vmware_host_memory_max{host_name=~\"$esxhost\"})"
    }
   ]
  },
  {
   "title": "Host CPU Usage ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(vmware_host_cpu_usage{host_name=~\"$esxhost\"}) * 100 / (vmware_host_cpu_max{host_name=~\"$esxhost\"})"
    }
   ]
  },
  {
   "title": "Datastores Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((vmware_datastore_capacity_size{host_name=~\"$esxhost\"}) - (vmware_datastore_freespace_size{host_name=~\"$esxhost\"})) * 100 / (vmware_datastore_capacity_size{host_name=~\"$esxhost\"})",
     "legendFormat": "{{ds_name}}"
    }
   ]
  },
  {
   "title": "Host Memory Percent Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(vmware_host_memory_usage{host_name=~\"$esxhost\"}) * 100 / (vmware_host_memory_max{host_name=~\"$esxhost\"})",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Number of VM's",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "count(vmware_vm_num_cpu)", "legendFormat": "VMs" }
   ]
  },
  {
   "title": "VM Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "rate(vmware_vm_mem_usage{host_name=~\"$esxhost\"}[5m]) / 4",
     "legendFormat": "{{ vm_name }}"
    }
   ]
  },
  {
   "title": "VM CPU usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "rate(vmware_vm_cpu_usagemhz{host_name=~\"$esxhost\"}[5m])",
     "legendFormat": "{{ vm_name }}"
    }
   ]
  }
 ]
}