{
 "title": "Ansible Tower Overview",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "License & Instance Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "License Type",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "awx_system_info" }
   ]
  },
  {
   "title": "Tower URL Link",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "awx_system_info" }
   ]
  },
  {
   "title": "Tower Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "awx_system_info" }
   ]
  },
  {
   "title": "Days Remaining on License",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Misc" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "awx_system_info" }
   ]
  },
  {
   "title": "Ansible Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "awx_system_info" }
   ]
  },
  {
   "title": "Tower Instances",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(awx_instance_info)" }
   ]
  },
  {
   "title": "Instance CPU Cores",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "awx_instance_cpu" }
   ]
  },
  {
   "title": "Instance Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "awx_instance_memory /1000" }
   ]
  },
  {
   "title": "Remaining Licensed Hosts ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "awx_license_instance_free", "legendFormat": "Total de Licenças" }
   ]
  },
  {
   "title": "Total Active Hosts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "awx_hosts_total{type=\"active\"}"
    }
   ]
  },
  { "title": "Job Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Successful Jobs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "awx_status_total{status=\"successful\"}"
    }
   ]
  },
  {
   "title": "Failed Jobs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "awx_status_total{status=\"failed\"}",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Job Launch Types",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(awx_instance_launch_type_total{launch_type=\"dependency\"})",
     "legendFormat": "Dependent "
    },
    {
     "expr": "sum(awx_instance_launch_type_total{launch_type=\"manual\"})",
     "legendFormat": "Manual"
    },
    {
     "expr": "sum(awx_instance_launch_type_total{launch_type=\"relaunch\"})",
     "legendFormat": "Manual"
    },
    {
     "expr": "sum(awx_instance_launch_type_total{launch_type=\"scheduled\"})",
     "legendFormat": "Scheduled"
    },
    {
     "expr": "sum(awx_instance_launch_type_total{launch_type=\"workflow\"})",
     "legendFormat": "Workflow"
    }
   ]
  },
  {
   "title": "Last 7 Days Job History",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "awx_status_total", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Last 7 Days Job History",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "awx_status_total", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Overview",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "awx_job_templates_total", "legendFormat": "Job Templates" },
    { "expr": "awx_inventories_total", "legendFormat": "Inventories" },
    { "expr": "awx_projects_total", "legendFormat": "Projects" },
    { "expr": "awx_organizations_total", "legendFormat": "Organizations" },
    { "expr": "awx_teams_total", "legendFormat": "Teams" },
    {
     "expr": "awx_workflow_job_templates_total",
     "legendFormat": "Workflow  Job Templates"
    }
   ]
  }
 ]
}